spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/health-tracker-db
    username: health-tracker
    password: health-tracker
    driver-class-name: org.postgresql.Driver
    database-platform: org.hibernate.dialect.PostgreSQLDialect